// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketServiceAPI.ScaffoldModels;

public partial class Stagesofticket
{
    public long Id { get; set; }

    public string StageDesc { get; set; }
}