// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketServiceAPI.ScaffoldModels;

public partial class Ticketsdetail
{
    public long Id { get; set; }

    public string Subject { get; set; }

    public string Description { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime? ModifyTime { get; set; }

    public long? RankId { get; set; }

    public string SupportPerson { get; set; }

    public long? Stage { get; set; }
}