// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TicketService.Models;

public partial class Menelsinfo
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long? Alko { get; set; }

    public int Age { get; set; }
}