// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBConnection.Models;

public partial class Candidatesdatum
{
    public long Id { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public int Role { get; set; }

    public virtual ICollection<Resume> Resumes { get; set; } = new List<Resume>();

    public virtual Rolesincompany RoleNavigation { get; set; }
}