// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal;
using System;
using System.Collections.Generic;

namespace DBConnection.Models;

public partial class CompanyDBContext : DbContext
{
    public CompanyDBContext()
    {
    }

    public CompanyDBContext(DbContextOptions<CompanyDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Candidatesdatum> Candidatesdata { get; set; }

    public virtual DbSet<Resume> Resumes { get; set; }

    public virtual DbSet<Rolesincompany> Rolesincompanies { get; set; }

    IConfiguration JsonData { get; init; } = new ConfigurationBuilder().AddJsonFile("Connections.json").Build(); //Getting server navigation from appsettings.json
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseMySql(JsonData["ConnectionStrings:DefaultConnection"], Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.40-mysql"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        
        modelBuilder.Entity<Candidatesdatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("candidatesdata");

            entity.HasIndex(e => e.Role, "candidatesdata_rolesincompany_FK");

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Full Name");

            entity.HasOne(d => d.RoleNavigation).WithMany(p => p.Candidatesdata)
                .HasForeignKey(d => d.Role)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("candidatesdata_rolesincompany_FK");
        });

        modelBuilder.Entity<Resume>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("resumes");

            entity.HasIndex(e => e.CandidatesResumesNo, "resumes_candidatesdata_FK");

            entity.Property(e => e.Date)
                .HasDefaultValueSql("'1900-01-01 00:00:00'")
                .HasColumnType("datetime");

            entity.HasOne(d => d.CandidatesResumesNoNavigation).WithMany(p => p.Resumes)
                .HasForeignKey(d => d.CandidatesResumesNo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("resumes_candidatesdata_FK");
        });

        modelBuilder.Entity<Rolesincompany>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("rolesincompany");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}