// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBConnection.Models;

public partial class Resume
{
    public long Id { get; set; }

    public long CandidatesResumesNo { get; set; }

    public bool IsArchive { get; set; }

    public DateTime Date { get; set; }

    public virtual Candidatesdatum CandidatesResumesNoNavigation { get; set; }
}