// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBConnection.Models;

public partial class Rolesincompany
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<Candidatesdatum> Candidatesdata { get; set; } = new List<Candidatesdatum>();
}